//-----------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------

namespace Turbo.Plugins.Jack.Extensions
{
    using System.Collections.Generic;

    using Turbo.Plugins.Default;

    public static class MissingSnoPowerExtensions
    {
        public static IController Hud { get; set; }

        // naming
        // end naming

        // missing
        public static ISnoPower Barbarian_Avalanche_v2_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(353458); }
        public static ISnoPower Crusader_LawsOfHope_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(323370); }
        public static ISnoPower Crusader_LawsOfHope_Passive2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(342299); }
        public static ISnoPower Crusader_LawsOfHope2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(342279); }
        public static ISnoPower Crusader_LawsOfJustice_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(323386); }
        public static ISnoPower Crusader_LawsOfJustice_Passive2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(342286); }
        public static ISnoPower Crusader_LawsOfJustice2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(342280); }
        public static ISnoPower Crusader_LawsOfValor_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(323387); }
        public static ISnoPower Crusader_LawsOfValor_Passive2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(342284); }
        public static ISnoPower Crusader_LawsOfValor2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(342281); }
        public static ISnoPower DemonHunter_Companion_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(365312); }
        public static ISnoPower DemonHunter_Preparation_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(324845); }
        public static ISnoPower Enchantress_Charm(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(102057); }
        public static ISnoPower Enchantress_Cripple(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(84469); }
        public static ISnoPower Enchantress_Disorient(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(101990); }
        public static ISnoPower Enchantress_FocusedMind(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(101425); }
        public static ISnoPower Enchantress_ForcefulPush(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(101969); }
        public static ISnoPower Enchantress_ForcefulPush2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(345292); }
        public static ISnoPower Enchantress_MassCharm(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(201524); }
        public static ISnoPower Enchantress_MassCharm2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(344565); }
        public static ISnoPower Enchantress_Melee_Instant(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(230238); }
        public static ISnoPower Enchantress_MissileWard(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(257687); }
        public static ISnoPower Enchantress_PoweredArmor(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(101461); }
        public static ISnoPower Enchantress_RunAway(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(186200); }
        public static ISnoPower Enchantress_ScorchedEarth(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(220872); }
        public static ISnoPower Enchantress_ScorchedEarth2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(345394); }
        public static ISnoPower Monk_MantraOfConviction_v2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(375088); }
        public static ISnoPower Monk_MantraOfConviction_v2_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(375089); }
        public static ISnoPower Monk_MantraOfEvasion_v2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(375049); }
        public static ISnoPower Monk_MantraOfEvasion_v2_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(375050); }
        public static ISnoPower Monk_MantraOfHealing_v2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(373143); }
        public static ISnoPower Monk_MantraOfHealing_v2_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(373154); }
        public static ISnoPower Monk_MantraOfRetribution_v2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(375082); }
        public static ISnoPower Monk_MantraOfRetribution_v2_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(375083); }
        public static ISnoPower Monk_MysticAlly_v2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(362102); }
        public static ISnoPower Monk_MysticAlly_v2_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(362118); }
        public static ISnoPower Scoundrel_Anatomy(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(30454); }
        public static ISnoPower Scoundrel_Bandage(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(30455); }
        public static ISnoPower Scoundrel_CripplingShot(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(95675); }
        public static ISnoPower Scoundrel_DirtyFighting(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(97436); }
        public static ISnoPower Scoundrel_Hysteria(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(200169); }
        public static ISnoPower Scoundrel_Multishot(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(365395); }
        public static ISnoPower Scoundrel_Multishot_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(366585); }
        public static ISnoPower Scoundrel_PoisonArrow(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(30460); }
        public static ISnoPower Scoundrel_PowerShot(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(95690); }
        public static ISnoPower Scoundrel_Ranged_Projectile(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(99902); }
        public static ISnoPower Scoundrel_RunAway(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(99904); }
        public static ISnoPower Scoundrel_Vanish(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(30464); }
        public static ISnoPower Templar_Guardian(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(30359); }
        public static ISnoPower Templar_Heal(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(344096); }
        public static ISnoPower Templar_Heal_110(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(257640); }
        public static ISnoPower Templar_Inspire(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(30356); }
        public static ISnoPower Templar_Intervene(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(93938); }
        public static ISnoPower Templar_Intervene_Proc(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(94008); }
        public static ISnoPower Templar_Intimidate(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(93901); }
        public static ISnoPower Templar_Loyalty(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(30357); }
        public static ISnoPower Templar_Melee_Instant(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(230239); }
        public static ISnoPower Templar_Onslaught(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(93888); }
        public static ISnoPower Templar_Onslaught2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(344099); }
        public static ISnoPower Templar_ShieldCharge(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(30360); }
        public static ISnoPower Templar_ShieldCharge2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(344098); }
        public static ISnoPower Wizard_Archon_ArcaneBlast_Cold(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392883); }
        public static ISnoPower Wizard_Archon_ArcaneBlast_Fire(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392884); }
        public static ISnoPower Wizard_Archon_ArcaneBlast_Lightning(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392885); }
        public static ISnoPower Wizard_Archon_ArcaneStrike_Cold(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392886); }
        public static ISnoPower Wizard_Archon_ArcaneStrike_Fire(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392887); }
        public static ISnoPower Wizard_Archon_ArcaneStrike_Lightning(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392888); }
        public static ISnoPower Wizard_Archon_Cancel(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(166616); }
        public static ISnoPower Wizard_Archon_DisintegrationWave_Cold(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392889); }
        public static ISnoPower Wizard_Archon_DisintegrationWave_Fire(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392890); }
        public static ISnoPower Wizard_Archon_DisintegrationWave_Lightning(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392891); }
        // end missing

        // set bonus
        public static IEnumerable<ISnoPower> AllSetBonusPowers(this ISnoPowerList powerList)
        {
            if (powerList.Barbarian_BulKathos() != null) yield return powerList.Barbarian_BulKathos();
            if (powerList.Barbarian_ImmortalKingCall2() != null) yield return powerList.Barbarian_ImmortalKingCall2();
            if (powerList.Barbarian_ImmortalKingCall4() != null) yield return powerList.Barbarian_ImmortalKingCall4();
            if (powerList.Barbarian_ImmortalKingCall6() != null) yield return powerList.Barbarian_ImmortalKingCall6();
            if (powerList.Barbarian_MightOfTheEarth2() != null) yield return powerList.Barbarian_MightOfTheEarth2();
            if (powerList.Barbarian_MightOfTheEarth4() != null) yield return powerList.Barbarian_MightOfTheEarth4();
            if (powerList.Barbarian_MightOfTheEarth6() != null) yield return powerList.Barbarian_MightOfTheEarth6();
            if (powerList.Barbarian_TheLegacyOfRaekor2() != null) yield return powerList.Barbarian_TheLegacyOfRaekor2();
            if (powerList.Barbarian_TheLegacyOfRaekor4() != null) yield return powerList.Barbarian_TheLegacyOfRaekor4();
            if (powerList.Barbarian_TheLegacyOfRaekor6() != null) yield return powerList.Barbarian_TheLegacyOfRaekor6();
            if (powerList.Barbarian_WrathOfTheWastes2() != null) yield return powerList.Barbarian_WrathOfTheWastes2();
            if (powerList.Barbarian_WrathOfTheWastes4() != null) yield return powerList.Barbarian_WrathOfTheWastes4();
            if (powerList.Barbarian_WrathOfTheWastes6() != null) yield return powerList.Barbarian_WrathOfTheWastes6();
            if (powerList.Crusader_NorvaldFervorPrimary() != null) yield return powerList.Crusader_NorvaldFervorPrimary();
            if (powerList.Crusader_NorvaldFervorSecondary() != null) yield return powerList.Crusader_NorvaldFervorSecondary();
            if (powerList.Crusader_ArmorOfAkkhan2() != null) yield return powerList.Crusader_ArmorOfAkkhan2();
            if (powerList.Crusader_ArmorOfAkkhan4() != null) yield return powerList.Crusader_ArmorOfAkkhan4();
            if (powerList.Crusader_ArmorOfAkkhan6() != null) yield return powerList.Crusader_ArmorOfAkkhan6();
            if (powerList.Crusader_RolandLegacy2() != null) yield return powerList.Crusader_RolandLegacy2();
            if (powerList.Crusader_RolandLegacy4() != null) yield return powerList.Crusader_RolandLegacy4();
            if (powerList.Crusader_RolandLegacy6() != null) yield return powerList.Crusader_RolandLegacy6();
            if (powerList.Crusader_SeekerOfTheLight2() != null) yield return powerList.Crusader_SeekerOfTheLight2();
            if (powerList.Crusader_SeekerOfTheLight4() != null) yield return powerList.Crusader_SeekerOfTheLight4();
            if (powerList.Crusader_SeekerOfTheLight6() != null) yield return powerList.Crusader_SeekerOfTheLight6();
            if (powerList.Crusader_ThornsOfTheInvoker2() != null) yield return powerList.Crusader_ThornsOfTheInvoker2();
            if (powerList.Crusader_ThornsOfTheInvoker4() != null) yield return powerList.Crusader_ThornsOfTheInvoker4();
            if (powerList.Crusader_ThornsOfTheInvoker6() != null) yield return powerList.Crusader_ThornsOfTheInvoker6();
            if (powerList.DemonHunter_DanettaHatredPrimary() != null) yield return powerList.DemonHunter_DanettaHatredPrimary();
            if (powerList.DemonHunter_DanettaHatredSecondary() != null) yield return powerList.DemonHunter_DanettaHatredSecondary();
            if (powerList.DemonHunter_EmbodimentOfTheMarauder2() != null) yield return powerList.DemonHunter_EmbodimentOfTheMarauder2();
            if (powerList.DemonHunter_EmbodimentOfTheMarauder4() != null) yield return powerList.DemonHunter_EmbodimentOfTheMarauder4();
            if (powerList.DemonHunter_EmbodimentOfTheMarauder6() != null) yield return powerList.DemonHunter_EmbodimentOfTheMarauder6();
            if (powerList.DemonHunter_NatalyaVengeance2() != null) yield return powerList.DemonHunter_NatalyaVengeance2();
            if (powerList.DemonHunter_NatalyaVengeance4() != null) yield return powerList.DemonHunter_NatalyaVengeance4();
            if (powerList.DemonHunter_NatalyaVengeance6() != null) yield return powerList.DemonHunter_NatalyaVengeance6();
            if (powerList.DemonHunter_TheShadowMantle2() != null) yield return powerList.DemonHunter_TheShadowMantle2();
            if (powerList.DemonHunter_TheShadowMantle4() != null) yield return powerList.DemonHunter_TheShadowMantle4();
            if (powerList.DemonHunter_TheShadowMantle6() != null) yield return powerList.DemonHunter_TheShadowMantle6();
            if (powerList.DemonHunter_UnhallowedEssence2() != null) yield return powerList.DemonHunter_UnhallowedEssence2();
            if (powerList.DemonHunter_UnhallowedEssence4() != null) yield return powerList.DemonHunter_UnhallowedEssence4();
            if (powerList.DemonHunter_UnhallowedEssence6() != null) yield return powerList.DemonHunter_UnhallowedEssence6();
            if (powerList.Monk_ShenlongPrimary() != null) yield return powerList.Monk_ShenlongPrimary();
            if (powerList.Monk_ShenlongSecondary() != null) yield return powerList.Monk_ShenlongSecondary();
            if (powerList.Monk_InnaMantra2() != null) yield return powerList.Monk_InnaMantra2();
            if (powerList.Monk_InnaMantra4() != null) yield return powerList.Monk_InnaMantra4();
            if (powerList.Monk_InnaMantra6() != null) yield return powerList.Monk_InnaMantra6();
            if (powerList.Monk_RaimentOfThousandStorms2() != null) yield return powerList.Monk_RaimentOfThousandStorms2();
            if (powerList.Monk_RaimentOfThousandStorms4() != null) yield return powerList.Monk_RaimentOfThousandStorms4();
            if (powerList.Monk_RaimentOfThousandStorms6() != null) yield return powerList.Monk_RaimentOfThousandStorms6();
            if (powerList.Monk_MonkeyKingGarb2() != null) yield return powerList.Monk_MonkeyKingGarb2();
            if (powerList.Monk_MonkeyKingGarb4() != null) yield return powerList.Monk_MonkeyKingGarb4();
            if (powerList.Monk_MonkeyKingGarb6() != null) yield return powerList.Monk_MonkeyKingGarb6();
            if (powerList.Monk_UlianaStratagem2() != null) yield return powerList.Monk_UlianaStratagem2();
            if (powerList.Monk_UlianaStratagem4() != null) yield return powerList.Monk_UlianaStratagem4();
            if (powerList.Monk_UlianaStratagem6() != null) yield return powerList.Monk_UlianaStratagem6();
            if (powerList.WitchDoctor_ManajumaWayPrimary() != null) yield return powerList.WitchDoctor_ManajumaWayPrimary();
            if (powerList.WitchDoctor_ManajumaWaySecondary() != null) yield return powerList.WitchDoctor_ManajumaWaySecondary();
            if (powerList.WitchDoctor_HellToothHarness2() != null) yield return powerList.WitchDoctor_HellToothHarness2();
            if (powerList.WitchDoctor_HellToothHarness4() != null) yield return powerList.WitchDoctor_HellToothHarness4();
            if (powerList.WitchDoctor_HellToothHarness6() != null) yield return powerList.WitchDoctor_HellToothHarness6();
            if (powerList.WitchDoctor_SpiritOfArachyr2() != null) yield return powerList.WitchDoctor_SpiritOfArachyr2();
            if (powerList.WitchDoctor_SpiritOfArachyr4() != null) yield return powerList.WitchDoctor_SpiritOfArachyr4();
            if (powerList.WitchDoctor_SpiritOfArachyr6() != null) yield return powerList.WitchDoctor_SpiritOfArachyr6();
            if (powerList.WitchDoctor_RaimentOfTheJadeHarvester2() != null) yield return powerList.WitchDoctor_RaimentOfTheJadeHarvester2();
            if (powerList.WitchDoctor_RaimentOfTheJadeHarvester4() != null) yield return powerList.WitchDoctor_RaimentOfTheJadeHarvester4();
            if (powerList.WitchDoctor_RaimentOfTheJadeHarvester6() != null) yield return powerList.WitchDoctor_RaimentOfTheJadeHarvester6();
            if (powerList.WitchDoctor_ZunimassaHaunt2() != null) yield return powerList.WitchDoctor_ZunimassaHaunt2();
            if (powerList.WitchDoctor_ZunimassaHaunt4() != null) yield return powerList.WitchDoctor_ZunimassaHaunt4();
            if (powerList.WitchDoctor_ZunimassaHaunt6() != null) yield return powerList.WitchDoctor_ZunimassaHaunt6();
            if (powerList.Wizard_ChantodoPrimary() != null) yield return powerList.Wizard_ChantodoPrimary();
            if (powerList.Wizard_ChantodoSecondary() != null) yield return powerList.Wizard_ChantodoSecondary();
            if (powerList.Wizard_VyrAmazingArcana2() != null) yield return powerList.Wizard_VyrAmazingArcana2();
            if (powerList.Wizard_VyrAmazingArcana4() != null) yield return powerList.Wizard_VyrAmazingArcana4();
            if (powerList.Wizard_VyrAmazingArcana6() != null) yield return powerList.Wizard_VyrAmazingArcana6();
            if (powerList.Wizard_TalRashaElements2() != null) yield return powerList.Wizard_TalRashaElements2();
            if (powerList.Wizard_TalRashaElements4() != null) yield return powerList.Wizard_TalRashaElements4();
            if (powerList.Wizard_TalRashaElements6() != null) yield return powerList.Wizard_TalRashaElements6();
            if (powerList.Wizard_FirebirdFinery2() != null) yield return powerList.Wizard_FirebirdFinery2();
            if (powerList.Wizard_FirebirdFinery4() != null) yield return powerList.Wizard_FirebirdFinery4();
            if (powerList.Wizard_FirebirdFinery6() != null) yield return powerList.Wizard_FirebirdFinery6();
            if (powerList.Wizard_DelsereMagnumOpus2() != null) yield return powerList.Wizard_DelsereMagnumOpus2();
            if (powerList.Wizard_DelsereMagnumOpus4() != null) yield return powerList.Wizard_DelsereMagnumOpus4();
            if (powerList.Wizard_DelsereMagnumOpus6() != null) yield return powerList.Wizard_DelsereMagnumOpus6();
            if (powerList.AshearaVestments4() != null) yield return powerList.AshearaVestments4();
            if (powerList.BastionsOfWillPrimary() != null) yield return powerList.BastionsOfWillPrimary();
            if (powerList.BastionsOfWillSecondary() != null) yield return powerList.BastionsOfWillSecondary();
            if (powerList.BlackthorneBattlegear4() != null) yield return powerList.BlackthorneBattlegear4();
            if (powerList.EndlessWalkPrimary() != null) yield return powerList.EndlessWalkPrimary();
            if (powerList.EndlessWalkSecondary() != null) yield return powerList.EndlessWalkSecondary();
            if (powerList.IstvanPairedBlades2() != null) yield return powerList.IstvanPairedBlades2();
            if (powerList.LegacyOfNightmares2() != null) yield return powerList.LegacyOfNightmares2();
            if (powerList.SageJourney2() != null) yield return powerList.SageJourney2();
        }

        public static ISnoPower Barbarian_BulKathos(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(434377); }
        public static ISnoPower Barbarian_ImmortalKingCall2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318760); }
        public static ISnoPower Barbarian_ImmortalKingCall4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429851); }
        public static ISnoPower Barbarian_ImmortalKingCall6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430684); }
        public static ISnoPower Barbarian_MightOfTheEarth2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318762); }
        public static ISnoPower Barbarian_MightOfTheEarth4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318418); }
        public static ISnoPower Barbarian_MightOfTheEarth6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(444521); }
        public static ISnoPower Barbarian_TheLegacyOfRaekor2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429665); }
        public static ISnoPower Barbarian_TheLegacyOfRaekor4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359563); }
        public static ISnoPower Barbarian_TheLegacyOfRaekor6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429673); }
        public static ISnoPower Barbarian_WrathOfTheWastes2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423206); }
        public static ISnoPower Barbarian_WrathOfTheWastes4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423205); }
        public static ISnoPower Barbarian_WrathOfTheWastes6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423226); }
        public static ISnoPower Crusader_NorvaldFervorPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(447291); }
        public static ISnoPower Crusader_NorvaldFervorSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(447290); }
        public static ISnoPower Crusader_ArmorOfAkkhan2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359584); }
        public static ISnoPower Crusader_ArmorOfAkkhan4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359585); }
        public static ISnoPower Crusader_ArmorOfAkkhan6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(445942); }
        public static ISnoPower Crusader_RolandLegacy2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430676); }
        public static ISnoPower Crusader_RolandLegacy4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430675); }
        public static ISnoPower Crusader_RolandLegacy6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(409428); }
        public static ISnoPower Crusader_SeekerOfTheLight2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(436428); }
        public static ISnoPower Crusader_SeekerOfTheLight4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(436426); }
        public static ISnoPower Crusader_SeekerOfTheLight6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(436427); }
        public static ISnoPower Crusader_ThornsOfTheInvoker2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(445829); }
        public static ISnoPower Crusader_ThornsOfTheInvoker4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(445639); }
        public static ISnoPower Crusader_ThornsOfTheInvoker6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(446511); }
        public static ISnoPower DemonHunter_DanettaHatredPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318380); }
        public static ISnoPower DemonHunter_DanettaHatredSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(447905); }
        public static ISnoPower DemonHunter_EmbodimentOfTheMarauder2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359561); }
        public static ISnoPower DemonHunter_EmbodimentOfTheMarauder4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359562); }
        public static ISnoPower DemonHunter_EmbodimentOfTheMarauder6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318832); }
        public static ISnoPower DemonHunter_NatalyaVengeance2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(402449); }
        public static ISnoPower DemonHunter_NatalyaVengeance4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429885); }
        public static ISnoPower DemonHunter_NatalyaVengeance6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(434964); }
        public static ISnoPower DemonHunter_TheShadowMantle2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318386); }
        public static ISnoPower DemonHunter_TheShadowMantle4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318876); }
        public static ISnoPower DemonHunter_TheShadowMantle6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(444522); }
        public static ISnoPower DemonHunter_UnhallowedEssence2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423230); }
        public static ISnoPower DemonHunter_UnhallowedEssence4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423244); }
        public static ISnoPower DemonHunter_UnhallowedEssence6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423228); }
        public static ISnoPower Monk_ShenlongPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(440568); }
        public static ISnoPower Monk_ShenlongSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(440569); }
        public static ISnoPower Monk_InnaMantra2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430685); }
        public static ISnoPower Monk_InnaMantra4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318435); }
        public static ISnoPower Monk_InnaMantra6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(449252); }
        public static ISnoPower Monk_RaimentOfThousandStorms2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(427799); }
        public static ISnoPower Monk_RaimentOfThousandStorms4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(427798); }
        public static ISnoPower Monk_RaimentOfThousandStorms6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430228); }
        public static ISnoPower Monk_MonkeyKingGarb2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(446762); }
        public static ISnoPower Monk_MonkeyKingGarb4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(446761); }
        public static ISnoPower Monk_MonkeyKingGarb6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(446562); }
        public static ISnoPower Monk_UlianaStratagem2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439311); }
        public static ISnoPower Monk_UlianaStratagem4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439310); }
        public static ISnoPower Monk_UlianaStratagem6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439312); }
        public static ISnoPower WitchDoctor_ManajumaWayPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(360491); }
        public static ISnoPower WitchDoctor_ManajumaWaySecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(440744); }
        public static ISnoPower WitchDoctor_HellToothHarness2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439309); }
        public static ISnoPower WitchDoctor_HellToothHarness4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(437710); }
        public static ISnoPower WitchDoctor_HellToothHarness6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(437711); }
        public static ISnoPower WitchDoctor_SpiritOfArachyr2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439303); }
        public static ISnoPower WitchDoctor_SpiritOfArachyr4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439308); }
        public static ISnoPower WitchDoctor_SpiritOfArachyr6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439309); }
        public static ISnoPower WitchDoctor_RaimentOfTheJadeHarvester2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(434967); }
        public static ISnoPower WitchDoctor_RaimentOfTheJadeHarvester4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(434969); }
        public static ISnoPower WitchDoctor_RaimentOfTheJadeHarvester6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359573); }
        public static ISnoPower WitchDoctor_ZunimassaHaunt2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318778); }
        public static ISnoPower WitchDoctor_ZunimassaHaunt4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430680); }
        public static ISnoPower WitchDoctor_ZunimassaHaunt6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429857); }
        public static ISnoPower Wizard_ChantodoPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(437844); }
        public static ISnoPower Wizard_ChantodoSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(440235); }
        public static ISnoPower Wizard_VyrAmazingArcana2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359574); }
        public static ISnoPower Wizard_VyrAmazingArcana4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(437840); }
        public static ISnoPower Wizard_VyrAmazingArcana6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(437843); }
        public static ISnoPower Wizard_TalRashaElements2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359555); }
        public static ISnoPower Wizard_TalRashaElements4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430672); }
        public static ISnoPower Wizard_TalRashaElements6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429855); }
        public static ISnoPower Wizard_FirebirdFinery2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359580); }
        public static ISnoPower Wizard_FirebirdFinery4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359581); }
        public static ISnoPower Wizard_FirebirdFinery6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(445814); }
        public static ISnoPower Wizard_DelsereMagnumOpus2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423237); }
        public static ISnoPower Wizard_DelsereMagnumOpus4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(450294); }
        public static ISnoPower Wizard_DelsereMagnumOpus6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423234); }
        public static ISnoPower AshearaVestments4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359558); }
        public static ISnoPower BastionsOfWillPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359583); }
        public static ISnoPower BastionsOfWillSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(434980); }
        public static ISnoPower BlackthorneBattlegear4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359556); }
        public static ISnoPower EndlessWalkPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(447541); }
        public static ISnoPower EndlessWalkSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(447553); }
        public static ISnoPower IstvanPairedBlades2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359582); }
        public static ISnoPower LegacyOfNightmares2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(445798); }
        public static ISnoPower SageJourney2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359560); }

        // Barbarian
        public static IBuff Barbarian_BulKathos(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(434377); }
        public static IBuff Barbarian_ImmortalKingCall2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(318760); }
        public static IBuff Barbarian_ImmortalKingCall4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(429851); }
        public static IBuff Barbarian_ImmortalKingCall6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(430684); }
        public static IBuff Barbarian_MightOfTheEarth2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(318762); }
        public static IBuff Barbarian_MightOfTheEarth4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(318418); }
        public static IBuff Barbarian_MightOfTheEarth6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(444521); }
        public static IBuff Barbarian_TheLegacyOfRaekor2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(429665); }
        public static IBuff Barbarian_TheLegacyOfRaekor4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359563); }
        public static IBuff Barbarian_TheLegacyOfRaekor6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(429673); }
        public static IBuff Barbarian_WrathOfTheWastes2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(423206); }
        public static IBuff Barbarian_WrathOfTheWastes4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(423205); }
        public static IBuff Barbarian_WrathOfTheWastes6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(423226); }
        public static IBuff Barbarian_Avalanche_v2_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(353458); }
        public static IEnumerable<IBuff> AllBarbarianSetBonusBuffs(this IPlayerPowerInfo playerPowers)
        {
            yield return playerPowers.Barbarian_BulKathos();
            yield return playerPowers.Barbarian_ImmortalKingCall2();
            yield return playerPowers.Barbarian_ImmortalKingCall4();
            yield return playerPowers.Barbarian_ImmortalKingCall6();
            yield return playerPowers.Barbarian_MightOfTheEarth2();
            yield return playerPowers.Barbarian_MightOfTheEarth4();
            yield return playerPowers.Barbarian_MightOfTheEarth6();
            yield return playerPowers.Barbarian_TheLegacyOfRaekor2();
            yield return playerPowers.Barbarian_TheLegacyOfRaekor4();
            yield return playerPowers.Barbarian_TheLegacyOfRaekor6();
            yield return playerPowers.Barbarian_WrathOfTheWastes2();
            yield return playerPowers.Barbarian_WrathOfTheWastes4();
            yield return playerPowers.Barbarian_WrathOfTheWastes6();
        }
        // end Barbarian

        // Crusader
        public static IBuff Crusader_NorvaldFervorPrimary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(447291); }
        public static IBuff Crusader_NorvaldFervorSecondary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(447290); }
        public static IBuff Crusader_ArmorOfAkkhan2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359584); }
        public static IBuff Crusader_ArmorOfAkkhan4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359585); }
        public static IBuff Crusader_ArmorOfAkkhan6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(445942); }
        public static IBuff Crusader_RolandLegacy2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(430676); }
        public static IBuff Crusader_RolandLegacy4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(430675); }
        public static IBuff Crusader_RolandLegacy6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(409428); }
        public static IBuff Crusader_SeekerOfTheLight2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(436428); }
        public static IBuff Crusader_SeekerOfTheLight4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(436426); }
        public static IBuff Crusader_SeekerOfTheLight6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(436427); }
        public static IBuff Crusader_ThornsOfTheInvoker2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(445829); }
        public static IBuff Crusader_ThornsOfTheInvoker4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(445639); }
        public static IBuff Crusader_ThornsOfTheInvoker6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(446511); }
        public static IBuff Crusader_LawsOfHope_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(323370); }
        public static IBuff Crusader_LawsOfHope_Passive2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(342299); }
        public static IBuff Crusader_LawsOfHope2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(342279); }
        public static IBuff Crusader_LawsOfJustice_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(323386); }
        public static IBuff Crusader_LawsOfJustice_Passive2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(342286); }
        public static IBuff Crusader_LawsOfJustice2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(342280); }
        public static IBuff Crusader_LawsOfValor_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(323387); }
        public static IBuff Crusader_LawsOfValor_Passive2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(342284); }
        public static IBuff Crusader_LawsOfValor2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(342281); }
        public static IEnumerable<IBuff> AllCrusaderSetBonusBuffs(this IPlayerPowerInfo playerPowers)
        {
            yield return playerPowers.Crusader_NorvaldFervorPrimary();
            yield return playerPowers.Crusader_NorvaldFervorSecondary();
            yield return playerPowers.Crusader_ArmorOfAkkhan2();
            yield return playerPowers.Crusader_ArmorOfAkkhan4();
            yield return playerPowers.Crusader_ArmorOfAkkhan6();
            yield return playerPowers.Crusader_RolandLegacy2();
            yield return playerPowers.Crusader_RolandLegacy4();
            yield return playerPowers.Crusader_RolandLegacy6();
            yield return playerPowers.Crusader_SeekerOfTheLight2();
            yield return playerPowers.Crusader_SeekerOfTheLight4();
            yield return playerPowers.Crusader_SeekerOfTheLight6();
            yield return playerPowers.Crusader_ThornsOfTheInvoker2();
            yield return playerPowers.Crusader_ThornsOfTheInvoker4();
            yield return playerPowers.Crusader_ThornsOfTheInvoker6();
        }
        // end Crusader

        // DemonHunter
        public static IBuff DemonHunter_DanettaHatredPrimary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(318380); }
        public static IBuff DemonHunter_DanettaHatredSecondary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(447905); }
        public static IBuff DemonHunter_EmbodimentOfTheMarauder2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359561); }
        public static IBuff DemonHunter_EmbodimentOfTheMarauder4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359562); }
        public static IBuff DemonHunter_EmbodimentOfTheMarauder6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(318832); }
        public static IBuff DemonHunter_NatalyaVengeance2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(402449); }
        public static IBuff DemonHunter_NatalyaVengeance4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(429885); }
        public static IBuff DemonHunter_NatalyaVengeance6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(434964); }
        public static IBuff DemonHunter_TheShadowMantle2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(318386); }
        public static IBuff DemonHunter_TheShadowMantle4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(318876); }
        public static IBuff DemonHunter_TheShadowMantle6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(444522); }
        public static IBuff DemonHunter_UnhallowedEssence2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(423230); }
        public static IBuff DemonHunter_UnhallowedEssence4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(423244); }
        public static IBuff DemonHunter_UnhallowedEssence6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(423228); }
        public static IBuff DemonHunter_Companion_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(365312); }
        public static IBuff DemonHunter_Preparation_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(324845); }
        public static IEnumerable<IBuff> AllDemonHunterSetBonusBuffs(this IPlayerPowerInfo playerPowers)
        {
            yield return playerPowers.DemonHunter_DanettaHatredPrimary();
            yield return playerPowers.DemonHunter_DanettaHatredSecondary();
            yield return playerPowers.DemonHunter_EmbodimentOfTheMarauder2();
            yield return playerPowers.DemonHunter_EmbodimentOfTheMarauder4();
            yield return playerPowers.DemonHunter_EmbodimentOfTheMarauder6();
            yield return playerPowers.DemonHunter_NatalyaVengeance2();
            yield return playerPowers.DemonHunter_NatalyaVengeance4();
            yield return playerPowers.DemonHunter_NatalyaVengeance6();
            yield return playerPowers.DemonHunter_TheShadowMantle2();
            yield return playerPowers.DemonHunter_TheShadowMantle4();
            yield return playerPowers.DemonHunter_TheShadowMantle6();
            yield return playerPowers.DemonHunter_UnhallowedEssence2();
            yield return playerPowers.DemonHunter_UnhallowedEssence4();
            yield return playerPowers.DemonHunter_UnhallowedEssence6();
        }
        // end DemonHunter

        // Monk
        public static IBuff Monk_ShenlongPrimary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(440568); }
        public static IBuff Monk_ShenlongSecondary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(440569); }
        public static IBuff Monk_InnaMantra2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(430685); }
        public static IBuff Monk_InnaMantra4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(318435); }
        public static IBuff Monk_InnaMantra6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(449252); }
        public static IBuff Monk_RaimentOfThousandStorms2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(427799); }
        public static IBuff Monk_RaimentOfThousandStorms4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(427798); }
        public static IBuff Monk_RaimentOfThousandStorms6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(430228); }
        public static IBuff Monk_MonkeyKingGarb2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(446762); }
        public static IBuff Monk_MonkeyKingGarb4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(446761); }
        public static IBuff Monk_MonkeyKingGarb6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(446562); }
        public static IBuff Monk_UlianaStratagem2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(439311); }
        public static IBuff Monk_UlianaStratagem4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(439310); }
        public static IBuff Monk_UlianaStratagem6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(439312); }
        public static IBuff Monk_MantraOfConviction_v2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(375088); }
        public static IBuff Monk_MantraOfConviction_v2_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(375089); }
        public static IBuff Monk_MantraOfEvasion_v2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(375049); }
        public static IBuff Monk_MantraOfEvasion_v2_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(375050); }
        public static IBuff Monk_MantraOfHealing_v2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(373143); }
        public static IBuff Monk_MantraOfHealing_v2_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(373154); }
        public static IBuff Monk_MantraOfRetribution_v2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(375082); }
        public static IBuff Monk_MantraOfRetribution_v2_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(375083); }
        public static IBuff Monk_MysticAlly_v2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(362102); }
        public static IBuff Monk_MysticAlly_v2_Passive(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(362118); }
        public static IEnumerable<IBuff> AllMonkSetBonusBuffs(this IPlayerPowerInfo playerPowers)
        {
            yield return playerPowers.Monk_ShenlongPrimary();
            yield return playerPowers.Monk_ShenlongSecondary();
            yield return playerPowers.Monk_InnaMantra2();
            yield return playerPowers.Monk_InnaMantra4();
            yield return playerPowers.Monk_InnaMantra6();
            yield return playerPowers.Monk_RaimentOfThousandStorms2();
            yield return playerPowers.Monk_RaimentOfThousandStorms4();
            yield return playerPowers.Monk_RaimentOfThousandStorms6();
            yield return playerPowers.Monk_MonkeyKingGarb2();
            yield return playerPowers.Monk_MonkeyKingGarb4();
            yield return playerPowers.Monk_MonkeyKingGarb6();
            yield return playerPowers.Monk_UlianaStratagem2();
            yield return playerPowers.Monk_UlianaStratagem4();
            yield return playerPowers.Monk_UlianaStratagem6();
        }
        // end Monk

        // WitchDoctor
        public static IBuff WitchDoctor_ManajumaWayPrimary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(360491); }
        public static IBuff WitchDoctor_ManajumaWaySecondary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(440744); }
        public static IBuff WitchDoctor_HellToothHarness2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(439309); }
        public static IBuff WitchDoctor_HellToothHarness4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(437710); }
        public static IBuff WitchDoctor_HellToothHarness6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(437711); }
        public static IBuff WitchDoctor_SpiritOfArachyr2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(439303); }
        public static IBuff WitchDoctor_SpiritOfArachyr4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(439308); }
        public static IBuff WitchDoctor_SpiritOfArachyr6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(439309); }
        public static IBuff WitchDoctor_RaimentOfTheJadeHarvester2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(434967); }
        public static IBuff WitchDoctor_RaimentOfTheJadeHarvester4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(434969); }
        public static IBuff WitchDoctor_RaimentOfTheJadeHarvester6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359573); }
        public static IBuff WitchDoctor_ZunimassaHaunt2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(318778); }
        public static IBuff WitchDoctor_ZunimassaHaunt4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(430680); }
        public static IBuff WitchDoctor_ZunimassaHaunt6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(429857); }
        public static IEnumerable<IBuff> AllWitchDoctorSetBonusBuffs(this IPlayerPowerInfo playerPowers)
        {
            yield return playerPowers.WitchDoctor_ManajumaWayPrimary();
            yield return playerPowers.WitchDoctor_ManajumaWaySecondary();
            yield return playerPowers.WitchDoctor_HellToothHarness2();
            yield return playerPowers.WitchDoctor_HellToothHarness4();
            yield return playerPowers.WitchDoctor_HellToothHarness6();
            yield return playerPowers.WitchDoctor_SpiritOfArachyr2();
            yield return playerPowers.WitchDoctor_SpiritOfArachyr4();
            yield return playerPowers.WitchDoctor_SpiritOfArachyr6();
            yield return playerPowers.WitchDoctor_RaimentOfTheJadeHarvester2();
            yield return playerPowers.WitchDoctor_RaimentOfTheJadeHarvester4();
            yield return playerPowers.WitchDoctor_RaimentOfTheJadeHarvester6();
            yield return playerPowers.WitchDoctor_ZunimassaHaunt2();
            yield return playerPowers.WitchDoctor_ZunimassaHaunt4();
            yield return playerPowers.WitchDoctor_ZunimassaHaunt6();
        }
        // end WitchDoctor

        // Wizard
        public static IBuff Wizard_ChantodoPrimary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(437844); }
        public static IBuff Wizard_ChantodoSecondary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(440235); }
        public static IBuff Wizard_VyrAmazingArcana2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359574); }
        public static IBuff Wizard_VyrAmazingArcana4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(437840); }
        public static IBuff Wizard_VyrAmazingArcana6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(437843); }
        public static IBuff Wizard_TalRashaElements2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359555); }
        public static IBuff Wizard_TalRashaElements4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(430672); }
        public static IBuff Wizard_TalRashaElements6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(429855); }
        public static IBuff Wizard_FirebirdFinery2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359580); }
        public static IBuff Wizard_FirebirdFinery4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359581); }
        public static IBuff Wizard_FirebirdFinery6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(445814); }
        public static IBuff Wizard_DelsereMagnumOpus2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(423237); }
        public static IBuff Wizard_DelsereMagnumOpus4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(450294); }
        public static IBuff Wizard_DelsereMagnumOpus6(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(423234); }
        public static IBuff Wizard_Archon_ArcaneBlast_Cold(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(392883); }
        public static IBuff Wizard_Archon_ArcaneBlast_Fire(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(392884); }
        public static IBuff Wizard_Archon_ArcaneBlast_Lightning(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(392885); }
        public static IBuff Wizard_Archon_ArcaneStrike_Cold(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(392886); }
        public static IBuff Wizard_Archon_ArcaneStrike_Fire(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(392887); }
        public static IBuff Wizard_Archon_ArcaneStrike_Lightning(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(392888); }
        public static IBuff Wizard_Archon_Cancel(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(166616); }
        public static IBuff Wizard_Archon_DisintegrationWave_Cold(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(392889); }
        public static IBuff Wizard_Archon_DisintegrationWave_Fire(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(392890); }
        public static IBuff Wizard_Archon_DisintegrationWave_Lightning(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(392891); }
        public static IEnumerable<IBuff> AllWizardSetBonusBuffs(this IPlayerPowerInfo playerPowers)
        {
            yield return playerPowers.Wizard_ChantodoPrimary();
            yield return playerPowers.Wizard_ChantodoSecondary();
            yield return playerPowers.Wizard_VyrAmazingArcana2();
            yield return playerPowers.Wizard_VyrAmazingArcana4();
            yield return playerPowers.Wizard_VyrAmazingArcana6();
            yield return playerPowers.Wizard_TalRashaElements2();
            yield return playerPowers.Wizard_TalRashaElements4();
            yield return playerPowers.Wizard_TalRashaElements6();
            yield return playerPowers.Wizard_FirebirdFinery2();
            yield return playerPowers.Wizard_FirebirdFinery4();
            yield return playerPowers.Wizard_FirebirdFinery6();
            yield return playerPowers.Wizard_DelsereMagnumOpus2();
            yield return playerPowers.Wizard_DelsereMagnumOpus4();
            yield return playerPowers.Wizard_DelsereMagnumOpus6();
        }
        // end Wizard

        // None
        public static IBuff AshearaVestments4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359558); }
        public static IBuff BastionsOfWillPrimary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359583); }
        public static IBuff BastionsOfWillSecondary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(434980); }
        public static IBuff BlackthorneBattlegear4(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359556); }
        public static IBuff EndlessWalkPrimary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(447541); }
        public static IBuff EndlessWalkSecondary(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(447553); }
        public static IBuff IstvanPairedBlades2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359582); }
        public static IBuff LegacyOfNightmares2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(445798); }
        public static IBuff SageJourney2(this IPlayerPowerInfo playerPowers) { return playerPowers.GetBuff(359560); }
        public static IEnumerable<IBuff> AllNoneSetBonusBuffs(this IPlayerPowerInfo playerPowers)
        {
            yield return playerPowers.AshearaVestments4();
            yield return playerPowers.BastionsOfWillPrimary();
            yield return playerPowers.BastionsOfWillSecondary();
            yield return playerPowers.BlackthorneBattlegear4();
            yield return playerPowers.EndlessWalkPrimary();
            yield return playerPowers.EndlessWalkSecondary();
            yield return playerPowers.IstvanPairedBlades2();
            yield return playerPowers.LegacyOfNightmares2();
            yield return playerPowers.SageJourney2();
        }
        // end None
        public static IEnumerable<IBuff> AllSetBonusBuffs(this IPlayerPowerInfo playerPowers)
        {
            yield return playerPowers.Barbarian_BulKathos();
            yield return playerPowers.Barbarian_ImmortalKingCall2();
            yield return playerPowers.Barbarian_ImmortalKingCall4();
            yield return playerPowers.Barbarian_ImmortalKingCall6();
            yield return playerPowers.Barbarian_MightOfTheEarth2();
            yield return playerPowers.Barbarian_MightOfTheEarth4();
            yield return playerPowers.Barbarian_MightOfTheEarth6();
            yield return playerPowers.Barbarian_TheLegacyOfRaekor2();
            yield return playerPowers.Barbarian_TheLegacyOfRaekor4();
            yield return playerPowers.Barbarian_TheLegacyOfRaekor6();
            yield return playerPowers.Barbarian_WrathOfTheWastes2();
            yield return playerPowers.Barbarian_WrathOfTheWastes4();
            yield return playerPowers.Barbarian_WrathOfTheWastes6();
            yield return playerPowers.Crusader_NorvaldFervorPrimary();
            yield return playerPowers.Crusader_NorvaldFervorSecondary();
            yield return playerPowers.Crusader_ArmorOfAkkhan2();
            yield return playerPowers.Crusader_ArmorOfAkkhan4();
            yield return playerPowers.Crusader_ArmorOfAkkhan6();
            yield return playerPowers.Crusader_RolandLegacy2();
            yield return playerPowers.Crusader_RolandLegacy4();
            yield return playerPowers.Crusader_RolandLegacy6();
            yield return playerPowers.Crusader_SeekerOfTheLight2();
            yield return playerPowers.Crusader_SeekerOfTheLight4();
            yield return playerPowers.Crusader_SeekerOfTheLight6();
            yield return playerPowers.Crusader_ThornsOfTheInvoker2();
            yield return playerPowers.Crusader_ThornsOfTheInvoker4();
            yield return playerPowers.Crusader_ThornsOfTheInvoker6();
            yield return playerPowers.DemonHunter_DanettaHatredPrimary();
            yield return playerPowers.DemonHunter_DanettaHatredSecondary();
            yield return playerPowers.DemonHunter_EmbodimentOfTheMarauder2();
            yield return playerPowers.DemonHunter_EmbodimentOfTheMarauder4();
            yield return playerPowers.DemonHunter_EmbodimentOfTheMarauder6();
            yield return playerPowers.DemonHunter_NatalyaVengeance2();
            yield return playerPowers.DemonHunter_NatalyaVengeance4();
            yield return playerPowers.DemonHunter_NatalyaVengeance6();
            yield return playerPowers.DemonHunter_TheShadowMantle2();
            yield return playerPowers.DemonHunter_TheShadowMantle4();
            yield return playerPowers.DemonHunter_TheShadowMantle6();
            yield return playerPowers.DemonHunter_UnhallowedEssence2();
            yield return playerPowers.DemonHunter_UnhallowedEssence4();
            yield return playerPowers.DemonHunter_UnhallowedEssence6();
            yield return playerPowers.Monk_ShenlongPrimary();
            yield return playerPowers.Monk_ShenlongSecondary();
            yield return playerPowers.Monk_InnaMantra2();
            yield return playerPowers.Monk_InnaMantra4();
            yield return playerPowers.Monk_InnaMantra6();
            yield return playerPowers.Monk_RaimentOfThousandStorms2();
            yield return playerPowers.Monk_RaimentOfThousandStorms4();
            yield return playerPowers.Monk_RaimentOfThousandStorms6();
            yield return playerPowers.Monk_MonkeyKingGarb2();
            yield return playerPowers.Monk_MonkeyKingGarb4();
            yield return playerPowers.Monk_MonkeyKingGarb6();
            yield return playerPowers.Monk_UlianaStratagem2();
            yield return playerPowers.Monk_UlianaStratagem4();
            yield return playerPowers.Monk_UlianaStratagem6();
            yield return playerPowers.WitchDoctor_ManajumaWayPrimary();
            yield return playerPowers.WitchDoctor_ManajumaWaySecondary();
            yield return playerPowers.WitchDoctor_HellToothHarness2();
            yield return playerPowers.WitchDoctor_HellToothHarness4();
            yield return playerPowers.WitchDoctor_HellToothHarness6();
            yield return playerPowers.WitchDoctor_SpiritOfArachyr2();
            yield return playerPowers.WitchDoctor_SpiritOfArachyr4();
            yield return playerPowers.WitchDoctor_SpiritOfArachyr6();
            yield return playerPowers.WitchDoctor_RaimentOfTheJadeHarvester2();
            yield return playerPowers.WitchDoctor_RaimentOfTheJadeHarvester4();
            yield return playerPowers.WitchDoctor_RaimentOfTheJadeHarvester6();
            yield return playerPowers.WitchDoctor_ZunimassaHaunt2();
            yield return playerPowers.WitchDoctor_ZunimassaHaunt4();
            yield return playerPowers.WitchDoctor_ZunimassaHaunt6();
            yield return playerPowers.Wizard_ChantodoPrimary();
            yield return playerPowers.Wizard_ChantodoSecondary();
            yield return playerPowers.Wizard_VyrAmazingArcana2();
            yield return playerPowers.Wizard_VyrAmazingArcana4();
            yield return playerPowers.Wizard_VyrAmazingArcana6();
            yield return playerPowers.Wizard_TalRashaElements2();
            yield return playerPowers.Wizard_TalRashaElements4();
            yield return playerPowers.Wizard_TalRashaElements6();
            yield return playerPowers.Wizard_FirebirdFinery2();
            yield return playerPowers.Wizard_FirebirdFinery4();
            yield return playerPowers.Wizard_FirebirdFinery6();
            yield return playerPowers.Wizard_DelsereMagnumOpus2();
            yield return playerPowers.Wizard_DelsereMagnumOpus4();
            yield return playerPowers.Wizard_DelsereMagnumOpus6();
            yield return playerPowers.AshearaVestments4();
            yield return playerPowers.BastionsOfWillPrimary();
            yield return playerPowers.BastionsOfWillSecondary();
            yield return playerPowers.BlackthorneBattlegear4();
            yield return playerPowers.EndlessWalkPrimary();
            yield return playerPowers.EndlessWalkSecondary();
            yield return playerPowers.IstvanPairedBlades2();
            yield return playerPowers.LegacyOfNightmares2();
            yield return playerPowers.SageJourney2();
        }

        // end set bonus
    }

    public class MissingSnoPowerExtensionsPlugin : BasePlugin
    {
        public MissingSnoPowerExtensionsPlugin()
        {
            Enabled = true;
        }

        public override void Load(IController hud)
        {
            base.Load(hud);
            MissingSnoPowerExtensions.Hud = hud;
            Enabled = false;
        }
    }
}
