//-----------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------

namespace Turbo.Plugins.Jack.Extensions
{
    using Turbo.Plugins.Default;

    public static class MissingSnoPowerExtensions
    {
        public static IController Hud { get; set; }

        // naming
        public static ISnoPower Monk_FistsOfThunder(this ISnoPowerList powerList) { return powerList.Monk_FistsofThunder; }
        public static ISnoPower Monk_Passive_Determination(this ISnoPowerList powerList) { return powerList.Monk_Passive_Provocation; }
        public static ISnoPower Monk_Passive_Alacrity(this ISnoPowerList powerList) { return powerList.Monk_Passive_GuidingLight; }
        public static ISnoPower WitchDoctor_WallOfDeath(this ISnoPowerList powerList) { return powerList.WitchDoctor_WallOfZombies; }
        public static ISnoPower WitchDoctor_Passive_SwamplandAttunement(this ISnoPowerList powerList) { return powerList.WitchDoctor_Passive_PhysicalAttunement; }
        // end naming

        // missing
        public static ISnoPower Wizard_Archon_ArcaneBlast_Cold(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392883); }
        public static ISnoPower Wizard_Archon_ArcaneBlast_Fire(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392884); }
        public static ISnoPower Wizard_Archon_ArcaneBlast_Lightning(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392885); }
        public static ISnoPower Wizard_Archon_ArcaneStrike_Cold(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392886); }
        public static ISnoPower Wizard_Archon_ArcaneStrike_Fire(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392887); }
        public static ISnoPower Wizard_Archon_ArcaneStrike_Lightning(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392888); }
        public static ISnoPower Wizard_Archon_Cancel(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(166616); }
        public static ISnoPower Wizard_Archon_DisintegrationWave_Cold(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392889); }
        public static ISnoPower Wizard_Archon_DisintegrationWave_Fire(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392890); }
        public static ISnoPower Wizard_Archon_DisintegrationWave_Lightning(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(392891); }
        public static ISnoPower Monk_MantraOfConviction_v2_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(375089); }
        public static ISnoPower Monk_MantraOfEvasion_v2_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(375050); }
        public static ISnoPower Monk_MantraOfHealing_v2_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(373154); }
        public static ISnoPower Monk_MantraOfRetribution_v2_Passive(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(375083); }
        // end missing

        // set bonus
        public static ISnoPower Set_Barbarian_BulKathos(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(434377); }
        public static ISnoPower Set_Barbarian_ImmortalKingCall2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318760); }
        public static ISnoPower Set_Barbarian_ImmortalKingCall4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429851); }
        public static ISnoPower Set_Barbarian_ImmortalKingCall6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430684); }
        public static ISnoPower Set_Barbarian_MightOfTheEarth2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318762); }
        public static ISnoPower Set_Barbarian_MightOfTheEarth4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318418); }
        public static ISnoPower Set_Barbarian_MightOfTheEarth6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(444521); }
        public static ISnoPower Set_Barbarian_TheLegacyOfRaekor2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429665); }
        public static ISnoPower Set_Barbarian_TheLegacyOfRaekor4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359563); }
        public static ISnoPower Set_Barbarian_TheLegacyOfRaekor6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429673); }
        public static ISnoPower Set_Barbarian_WrathOfTheWastes2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423206); }
        public static ISnoPower Set_Barbarian_WrathOfTheWastes4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423205); }
        public static ISnoPower Set_Barbarian_WrathOfTheWastes6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423226); }
        public static ISnoPower Set_Crusader_NorvaldFervorPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(447291); }
        public static ISnoPower Set_Crusader_NorvaldFervorSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(447290); }
        public static ISnoPower Set_Crusader_ArmorOfAkkhan2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359584); }
        public static ISnoPower Set_Crusader_ArmorOfAkkhan4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359585); }
        public static ISnoPower Set_Crusader_ArmorOfAkkhan6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(445942); }
        public static ISnoPower Set_Crusader_RolandLegacy2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430676); }
        public static ISnoPower Set_Crusader_RolandLegacy4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430675); }
        public static ISnoPower Set_Crusader_RolandLegacy6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(409428); }
        public static ISnoPower Set_Crusader_SeekerOfTheLight2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(436428); }
        public static ISnoPower Set_Crusader_SeekerOfTheLight4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(436426); }
        public static ISnoPower Set_Crusader_SeekerOfTheLight6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(436427); }
        public static ISnoPower Set_Crusader_ThornsOfTheInvoker2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(445829); }
        public static ISnoPower Set_Crusader_ThornsOfTheInvoker4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(445639); }
        public static ISnoPower Set_Crusader_ThornsOfTheInvoker6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(446511); }
        public static ISnoPower Set_DemonHunter_DanettaHatredPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318380); }
        public static ISnoPower Set_DemonHunter_DanettaHatredSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(447905); }
        public static ISnoPower Set_DemonHunter_EmbodimentOfTheMarauder2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359561); }
        public static ISnoPower Set_DemonHunter_EmbodimentOfTheMarauder4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359562); }
        public static ISnoPower Set_DemonHunter_EmbodimentOfTheMarauder6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318832); }
        public static ISnoPower Set_DemonHunter_NatalyaVengeance2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(402449); }
        public static ISnoPower Set_DemonHunter_NatalyaVengeance4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429885); }
        public static ISnoPower Set_DemonHunter_NatalyaVengeance6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(434964); }
        public static ISnoPower Set_DemonHunter_TheShadowMantle2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318386); }
        public static ISnoPower Set_DemonHunter_TheShadowMantle4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318876); }
        public static ISnoPower Set_DemonHunter_TheShadowMantle6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(444522); }
        public static ISnoPower Set_DemonHunter_UnhallowedEssence2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423230); }
        public static ISnoPower Set_DemonHunter_UnhallowedEssence4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423244); }
        public static ISnoPower Set_DemonHunter_UnhallowedEssence6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423228); }
        public static ISnoPower Set_Monk_ShenlongPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(440568); }
        public static ISnoPower Set_Monk_ShenlongSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(440569); }
        public static ISnoPower Set_Monk_InnaMantra2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430685); }
        public static ISnoPower Set_Monk_InnaMantra4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318435); }
        public static ISnoPower Set_Monk_InnaMantra6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(449252); }
        public static ISnoPower Set_Monk_RaimentOfThousandStorms2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(427799); }
        public static ISnoPower Set_Monk_RaimentOfThousandStorms4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(427798); }
        public static ISnoPower Set_Monk_RaimentOfThousandStorms6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430228); }
        public static ISnoPower Set_Monk_MonkeyKingGarb2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(446762); }
        public static ISnoPower Set_Monk_MonkeyKingGarb4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(446761); }
        public static ISnoPower Set_Monk_MonkeyKingGarb6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(446562); }
        public static ISnoPower Set_Monk_UlianaStratagem2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439311); }
        public static ISnoPower Set_Monk_UlianaStratagem4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439310); }
        public static ISnoPower Set_Monk_UlianaStratagem6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439312); }
        public static ISnoPower Set_Witchdoctor_ManajumaWayPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(360491); }
        public static ISnoPower Set_Witchdoctor_ManajumaWaySecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(440744); }
        public static ISnoPower Set_Witchdoctor_HellToothHarness2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439309); }
        public static ISnoPower Set_Witchdoctor_HellToothHarness4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(437710); }
        public static ISnoPower Set_Witchdoctor_HellToothHarness6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(437711); }
        public static ISnoPower Set_Witchdoctor_SpiritOfArachyr2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439303); }
        public static ISnoPower Set_Witchdoctor_SpiritOfArachyr4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439308); }
        public static ISnoPower Set_Witchdoctor_SpiritOfArachyr6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(439309); }
        public static ISnoPower Set_Witchdoctor_RaimentOfTheJadeHarvester2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(434967); }
        public static ISnoPower Set_Witchdoctor_RaimentOfTheJadeHarvester4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(434969); }
        public static ISnoPower Set_Witchdoctor_RaimentOfTheJadeHarvester6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359573); }
        public static ISnoPower Set_Witchdoctor_ZunimassaHaunt2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(318778); }
        public static ISnoPower Set_Witchdoctor_ZunimassaHaunt4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430680); }
        public static ISnoPower Set_Witchdoctor_ZunimassaHaunt6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429857); }
        public static ISnoPower Set_Wizard_ChantodoPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(437844); }
        public static ISnoPower Set_Wizard_ChantodoSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(440235); }
        public static ISnoPower Set_Wizard_VyrAmazingArcana2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359574); }
        public static ISnoPower Set_Wizard_VyrAmazingArcana4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(437840); }
        public static ISnoPower Set_Wizard_VyrAmazingArcana6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(437843); }
        public static ISnoPower Set_Wizard_TalRashaElements2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359555); }
        public static ISnoPower Set_Wizard_TalRashaElements4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(430672); }
        public static ISnoPower Set_Wizard_TalRashaElements6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(429855); }
        public static ISnoPower Set_Wizard_FirebirdFinery2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359580); }
        public static ISnoPower Set_Wizard_FirebirdFinery4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359581); }
        public static ISnoPower Set_Wizard_FirebirdFinery6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(445814); }
        public static ISnoPower Set_Wizard_DelsereMagnumOpus2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423237); }
        public static ISnoPower Set_Wizard_DelsereMagnumOpus4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(450294); }
        public static ISnoPower Set_Wizard_DelsereMagnumOpus6(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(423234); }
        public static ISnoPower Set_AshearaVestments4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359558); }
        public static ISnoPower Set_BastionsOfWillPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359583); }
        public static ISnoPower Set_BastionsOfWillSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(434980); }
        public static ISnoPower Set_BlackthorneBattlegear4(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359556); }
        public static ISnoPower Set_EndlessWalkPrimary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(447541); }
        public static ISnoPower Set_EndlessWalkSecondary(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(447553); }
        public static ISnoPower Set_IstvanPairedBlades2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359582); }
        public static ISnoPower Set_LegacyOfNightmares2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(445798); }
        public static ISnoPower Set_SageJourney2(this ISnoPowerList powerList) { return Hud.Sno.GetSnoPower(359560); }
        // end set bonus
    }

    public class MissingSnoPowerExtensionsPlugin : BasePlugin
    {
        public MissingSnoPowerExtensionsPlugin()
        {
            Enabled = true;
        }

        public override void Load(IController hud)
        {
            base.Load(hud);
            MissingSnoPowerExtensions.Hud = hud;
            Enabled = false;
        }
    }
}
